site_name: Cooler
theme: 
  name: material
  language: zh
  palette:
    primary: teal
  logo: assets/logo.svg
repo_url: https://github.com/Cooler-dev/Cooler
repo_name: Cooler-dev/Cooler
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs/
nav :
  - 首页: index.md