name: Build docs
on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/*'
      - 'mkdocs.yml'
      - '.github/workflows/build-docs.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs
      - run: mkdocs build
      - run: echo "cooler.redish101.tk" >> public/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: Cooler-bot
          user_email: Cooler-bot@users.noreply.github.com
