name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/cooler-dev/cooler:$(date +%s)
  
  publish:
     runs-on: ubuntu-latest
     steps:
     - name: Publish the Docker image
       run: docker push ghcr.io/cooler-dev/cooler:$(date +%s)
